#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 106
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 1

enum {
  sym_keyword = 1,
  anon_sym_DOT = 2,
  anon_sym_PIPE = 3,
  anon_sym_COLON_EQ = 4,
  sym_number = 5,
  anon_sym_SQUOTE = 6,
  aux_sym_string_token1 = 7,
  anon_sym_POUND = 8,
  aux_sym_symbol_token1 = 9,
  sym_identifier = 10,
  sym_binary_operator = 11,
  anon_sym_CARET = 12,
  anon_sym_LBRACE = 13,
  anon_sym_RBRACE = 14,
  anon_sym_POUND_LBRACK = 15,
  anon_sym_RBRACK = 16,
  anon_sym_LPAREN = 17,
  anon_sym_RPAREN = 18,
  sym_block_argument = 19,
  anon_sym_LBRACK = 20,
  sym_method = 21,
  sym_temporaries = 22,
  sym_selector = 23,
  sym_unary_selector = 24,
  sym_binary_selector = 25,
  sym_keyword_selector = 26,
  sym_unary_message = 27,
  sym_binary_message = 28,
  sym_keyword_message = 29,
  sym_assignment = 30,
  sym_string = 31,
  sym_symbol = 32,
  sym_statement = 33,
  sym_return = 34,
  sym_dynamic_array = 35,
  sym_byte_array = 36,
  sym_parenthesized_expression = 37,
  sym_block = 38,
  sym_primary = 39,
  sym_expression = 40,
  aux_sym_method_repeat1 = 41,
  aux_sym_temporaries_repeat1 = 42,
  aux_sym_keyword_selector_repeat1 = 43,
  aux_sym_keyword_message_repeat1 = 44,
  aux_sym_dynamic_array_repeat1 = 45,
  aux_sym_byte_array_repeat1 = 46,
  aux_sym_block_repeat1 = 47,
  aux_sym_block_repeat2 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_keyword] = "keyword",
  [anon_sym_DOT] = ".",
  [anon_sym_PIPE] = "|",
  [anon_sym_COLON_EQ] = ":=",
  [sym_number] = "number",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_POUND] = "#",
  [aux_sym_symbol_token1] = "symbol_token1",
  [sym_identifier] = "identifier",
  [sym_binary_operator] = "binary_operator",
  [anon_sym_CARET] = "^",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_POUND_LBRACK] = "#[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_block_argument] = "block_argument",
  [anon_sym_LBRACK] = "[",
  [sym_method] = "method",
  [sym_temporaries] = "temporaries",
  [sym_selector] = "selector",
  [sym_unary_selector] = "unary_selector",
  [sym_binary_selector] = "binary_selector",
  [sym_keyword_selector] = "keyword_selector",
  [sym_unary_message] = "unary_message",
  [sym_binary_message] = "binary_message",
  [sym_keyword_message] = "keyword_message",
  [sym_assignment] = "assignment",
  [sym_string] = "string",
  [sym_symbol] = "symbol",
  [sym_statement] = "statement",
  [sym_return] = "return",
  [sym_dynamic_array] = "dynamic_array",
  [sym_byte_array] = "byte_array",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_block] = "block",
  [sym_primary] = "primary",
  [sym_expression] = "expression",
  [aux_sym_method_repeat1] = "method_repeat1",
  [aux_sym_temporaries_repeat1] = "temporaries_repeat1",
  [aux_sym_keyword_selector_repeat1] = "keyword_selector_repeat1",
  [aux_sym_keyword_message_repeat1] = "keyword_message_repeat1",
  [aux_sym_dynamic_array_repeat1] = "dynamic_array_repeat1",
  [aux_sym_byte_array_repeat1] = "byte_array_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_block_repeat2] = "block_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_keyword] = sym_keyword,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_COLON_EQ] = anon_sym_COLON_EQ,
  [sym_number] = sym_number,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_symbol_token1] = aux_sym_symbol_token1,
  [sym_identifier] = sym_identifier,
  [sym_binary_operator] = sym_binary_operator,
  [anon_sym_CARET] = anon_sym_CARET,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_POUND_LBRACK] = anon_sym_POUND_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_block_argument] = sym_block_argument,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [sym_method] = sym_method,
  [sym_temporaries] = sym_temporaries,
  [sym_selector] = sym_selector,
  [sym_unary_selector] = sym_unary_selector,
  [sym_binary_selector] = sym_binary_selector,
  [sym_keyword_selector] = sym_keyword_selector,
  [sym_unary_message] = sym_unary_message,
  [sym_binary_message] = sym_binary_message,
  [sym_keyword_message] = sym_keyword_message,
  [sym_assignment] = sym_assignment,
  [sym_string] = sym_string,
  [sym_symbol] = sym_symbol,
  [sym_statement] = sym_statement,
  [sym_return] = sym_return,
  [sym_dynamic_array] = sym_dynamic_array,
  [sym_byte_array] = sym_byte_array,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_block] = sym_block,
  [sym_primary] = sym_primary,
  [sym_expression] = sym_expression,
  [aux_sym_method_repeat1] = aux_sym_method_repeat1,
  [aux_sym_temporaries_repeat1] = aux_sym_temporaries_repeat1,
  [aux_sym_keyword_selector_repeat1] = aux_sym_keyword_selector_repeat1,
  [aux_sym_keyword_message_repeat1] = aux_sym_keyword_message_repeat1,
  [aux_sym_dynamic_array_repeat1] = aux_sym_dynamic_array_repeat1,
  [aux_sym_byte_array_repeat1] = aux_sym_byte_array_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_block_repeat2] = aux_sym_block_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_keyword] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_symbol_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_CARET] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_block_argument] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_temporaries] = {
    .visible = true,
    .named = true,
  },
  [sym_selector] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_unary_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_selector] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_message] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_message] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_message] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_return] = {
    .visible = true,
    .named = true,
  },
  [sym_dynamic_array] = {
    .visible = true,
    .named = true,
  },
  [sym_byte_array] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_primary] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [sym_expression] = {
    .visible = false,
    .named = true,
    .supertype = true,
  },
  [aux_sym_method_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_temporaries_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_keyword_selector_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_keyword_message_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dynamic_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_byte_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == ':') ADVANCE(3);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '^') ADVANCE(26);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '|') ADVANCE(12);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead == '!' ||
          ('%' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '~') ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 1:
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '=') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(13);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 5:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 6:
      if (eof) ADVANCE(9);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == ':') ADVANCE(5);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '^') ADVANCE(26);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(17);
      if (lookahead == '(') ADVANCE(31);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == '[') ADVANCE(34);
      if (lookahead == '^') ADVANCE(26);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '|') ADVANCE(11);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == ')') ADVANCE(32);
      if (lookahead == '.') ADVANCE(10);
      if (lookahead == ':') ADVANCE(2);
      if (lookahead == ']') ADVANCE(30);
      if (lookahead == '}') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(8)
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '/') ||
          ('<' <= lookahead && lookahead <= '@') ||
          ('|' <= lookahead && lookahead <= '~')) ADVANCE(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(25);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_COLON_EQ);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_keyword);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'r') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead == '[') ADVANCE(29);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_symbol_token1);
      if (('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == ':') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_binary_operator);
      if (lookahead == '!' ||
          lookahead == '%' ||
          lookahead == '&' ||
          ('*' <= lookahead && lookahead <= '-') ||
          lookahead == '/' ||
          ('<' <= lookahead && lookahead <= '@') ||
          lookahead == '|' ||
          lookahead == '~') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_CARET);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_POUND_LBRACK);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_block_argument);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 6},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 6},
  [11] = {.lex_state = 6},
  [12] = {.lex_state = 6},
  [13] = {.lex_state = 6},
  [14] = {.lex_state = 6},
  [15] = {.lex_state = 6},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 6},
  [21] = {.lex_state = 6},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 6},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 7},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 8},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 8},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 8},
  [44] = {.lex_state = 8},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 8},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 8},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 8},
  [51] = {.lex_state = 8},
  [52] = {.lex_state = 8},
  [53] = {.lex_state = 8},
  [54] = {.lex_state = 8},
  [55] = {.lex_state = 8},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 8},
  [58] = {.lex_state = 8},
  [59] = {.lex_state = 8},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 8},
  [62] = {.lex_state = 8},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 8},
  [65] = {.lex_state = 8},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 6},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 6},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 6},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 6},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 6},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 18},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 6},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 6},
  [105] = {.lex_state = 18},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_keyword] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_COLON_EQ] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_binary_operator] = ACTIONS(1),
    [anon_sym_CARET] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_POUND_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_block_argument] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
  },
  [1] = {
    [sym_method] = STATE(101),
    [sym_selector] = STATE(4),
    [sym_unary_selector] = STATE(34),
    [sym_binary_selector] = STATE(34),
    [sym_keyword_selector] = STATE(34),
    [aux_sym_keyword_selector_repeat1] = STATE(27),
    [sym_keyword] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym_binary_operator] = ACTIONS(7),
  },
  [2] = {
    [sym_temporaries] = STATE(7),
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(78),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [aux_sym_block_repeat1] = STATE(89),
    [anon_sym_DOT] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(11),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [sym_block_argument] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
  [3] = {
    [sym_temporaries] = STATE(8),
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(66),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [aux_sym_temporaries_repeat1] = STATE(70),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_PIPE] = ACTIONS(37),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(39),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
  [4] = {
    [sym_temporaries] = STATE(6),
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(73),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [aux_sym_method_repeat1] = STATE(69),
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_DOT] = ACTIONS(45),
    [anon_sym_PIPE] = ACTIONS(47),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
  [5] = {
    [sym_temporaries] = STATE(10),
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(86),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [anon_sym_DOT] = ACTIONS(49),
    [anon_sym_PIPE] = ACTIONS(47),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
  [6] = {
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(91),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [aux_sym_method_repeat1] = STATE(87),
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_DOT] = ACTIONS(45),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
  [7] = {
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(66),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [anon_sym_DOT] = ACTIONS(35),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(41),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
  [8] = {
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(86),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [anon_sym_DOT] = ACTIONS(49),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
  [9] = {
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(94),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_DOT] = ACTIONS(55),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
  [10] = {
    [sym_unary_message] = STATE(57),
    [sym_binary_message] = STATE(57),
    [sym_keyword_message] = STATE(57),
    [sym_assignment] = STATE(57),
    [sym_string] = STATE(45),
    [sym_symbol] = STATE(45),
    [sym_statement] = STATE(67),
    [sym_return] = STATE(71),
    [sym_dynamic_array] = STATE(45),
    [sym_byte_array] = STATE(45),
    [sym_parenthesized_expression] = STATE(45),
    [sym_block] = STATE(45),
    [sym_primary] = STATE(57),
    [sym_expression] = STATE(62),
    [anon_sym_DOT] = ACTIONS(57),
    [sym_number] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_POUND] = ACTIONS(17),
    [sym_identifier] = ACTIONS(19),
    [anon_sym_CARET] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_POUND_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_CARET,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      sym_expression,
    STATE(71), 1,
      sym_return,
    STATE(93), 1,
      sym_statement,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [55] = 15,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_CARET,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      sym_expression,
    STATE(71), 1,
      sym_return,
    STATE(93), 1,
      sym_statement,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [110] = 15,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_CARET,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      sym_expression,
    STATE(71), 1,
      sym_return,
    STATE(93), 1,
      sym_statement,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [165] = 15,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_CARET,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      sym_expression,
    STATE(71), 1,
      sym_return,
    STATE(93), 1,
      sym_statement,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [220] = 15,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_CARET,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    STATE(62), 1,
      sym_expression,
    STATE(71), 1,
      sym_return,
    STATE(93), 1,
      sym_statement,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [275] = 14,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_CARET,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(62), 1,
      sym_expression,
    STATE(71), 1,
      sym_return,
    STATE(93), 1,
      sym_statement,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [327] = 12,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(67), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [373] = 12,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [419] = 11,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(61), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [462] = 11,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(65), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [505] = 11,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(60), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [548] = 11,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(39), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [591] = 11,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(64), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [634] = 11,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(37), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [677] = 11,
    ACTIONS(13), 1,
      sym_number,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND,
    ACTIONS(19), 1,
      sym_identifier,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_POUND_LBRACK,
    ACTIONS(29), 1,
      anon_sym_LPAREN,
    ACTIONS(33), 1,
      anon_sym_LBRACK,
    STATE(38), 1,
      sym_expression,
    STATE(57), 5,
      sym_unary_message,
      sym_binary_message,
      sym_keyword_message,
      sym_assignment,
      sym_primary,
    STATE(45), 6,
      sym_string,
      sym_symbol,
      sym_dynamic_array,
      sym_byte_array,
      sym_parenthesized_expression,
      sym_block,
  [720] = 4,
    ACTIONS(73), 1,
      sym_keyword,
    STATE(26), 1,
      aux_sym_keyword_selector_repeat1,
    ACTIONS(76), 2,
      anon_sym_POUND,
      sym_identifier,
    ACTIONS(71), 10,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_PIPE,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [743] = 4,
    ACTIONS(3), 1,
      sym_keyword,
    STATE(26), 1,
      aux_sym_keyword_selector_repeat1,
    ACTIONS(80), 2,
      anon_sym_POUND,
      sym_identifier,
    ACTIONS(78), 10,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_PIPE,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [766] = 2,
    ACTIONS(76), 2,
      anon_sym_POUND,
      sym_identifier,
    ACTIONS(71), 11,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_PIPE,
      sym_keyword,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [784] = 5,
    ACTIONS(84), 1,
      anon_sym_PIPE,
    ACTIONS(86), 1,
      anon_sym_POUND,
    ACTIONS(88), 1,
      sym_identifier,
    STATE(70), 1,
      aux_sym_temporaries_repeat1,
    ACTIONS(82), 9,
      anon_sym_DOT,
      sym_number,
      anon_sym_SQUOTE,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [808] = 2,
    ACTIONS(93), 1,
      anon_sym_POUND,
    ACTIONS(91), 11,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_PIPE,
      sym_number,
      anon_sym_SQUOTE,
      sym_identifier,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [825] = 2,
    ACTIONS(97), 1,
      anon_sym_POUND,
    ACTIONS(95), 11,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_PIPE,
      sym_number,
      anon_sym_SQUOTE,
      sym_identifier,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [842] = 2,
    ACTIONS(101), 1,
      anon_sym_POUND,
    ACTIONS(99), 11,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_number,
      anon_sym_SQUOTE,
      sym_identifier,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [859] = 2,
    ACTIONS(86), 1,
      anon_sym_POUND,
    ACTIONS(82), 11,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_number,
      anon_sym_SQUOTE,
      sym_identifier,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [876] = 2,
    ACTIONS(105), 1,
      anon_sym_POUND,
    ACTIONS(103), 11,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_PIPE,
      sym_number,
      anon_sym_SQUOTE,
      sym_identifier,
      anon_sym_CARET,
      anon_sym_LBRACE,
      anon_sym_POUND_LBRACK,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
  [893] = 4,
    ACTIONS(109), 1,
      sym_keyword,
    ACTIONS(112), 1,
      sym_identifier,
    STATE(35), 1,
      aux_sym_keyword_message_repeat1,
    ACTIONS(107), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [911] = 3,
    ACTIONS(116), 1,
      anon_sym_COLON_EQ,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(114), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [927] = 5,
    ACTIONS(120), 1,
      sym_keyword,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_binary_operator,
    STATE(40), 1,
      aux_sym_keyword_message_repeat1,
    ACTIONS(107), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [947] = 3,
    ACTIONS(123), 1,
      sym_identifier,
    STATE(40), 1,
      aux_sym_keyword_message_repeat1,
    ACTIONS(127), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [963] = 5,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_binary_operator,
    ACTIONS(131), 1,
      sym_keyword,
    STATE(40), 1,
      aux_sym_keyword_message_repeat1,
    ACTIONS(129), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [983] = 4,
    ACTIONS(135), 1,
      sym_keyword,
    ACTIONS(138), 1,
      sym_identifier,
    STATE(35), 1,
      aux_sym_keyword_message_repeat1,
    ACTIONS(133), 6,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1001] = 2,
    ACTIONS(142), 1,
      sym_identifier,
    ACTIONS(140), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1014] = 2,
    ACTIONS(146), 1,
      sym_identifier,
    ACTIONS(144), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1027] = 2,
    ACTIONS(150), 1,
      sym_identifier,
    ACTIONS(148), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1040] = 2,
    ACTIONS(154), 1,
      sym_identifier,
    ACTIONS(152), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1053] = 2,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(114), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1066] = 2,
    ACTIONS(158), 1,
      sym_identifier,
    ACTIONS(156), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1079] = 2,
    ACTIONS(162), 1,
      sym_identifier,
    ACTIONS(160), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1092] = 2,
    ACTIONS(166), 1,
      sym_identifier,
    ACTIONS(164), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1105] = 2,
    ACTIONS(170), 1,
      sym_identifier,
    ACTIONS(168), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1118] = 2,
    ACTIONS(174), 1,
      sym_identifier,
    ACTIONS(172), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1131] = 2,
    ACTIONS(178), 1,
      sym_identifier,
    ACTIONS(176), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1144] = 2,
    ACTIONS(182), 1,
      sym_identifier,
    ACTIONS(180), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1157] = 2,
    ACTIONS(186), 1,
      sym_identifier,
    ACTIONS(184), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1170] = 2,
    ACTIONS(190), 1,
      sym_identifier,
    ACTIONS(188), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1183] = 2,
    ACTIONS(194), 1,
      sym_identifier,
    ACTIONS(192), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1196] = 2,
    ACTIONS(198), 1,
      sym_identifier,
    ACTIONS(196), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1209] = 2,
    ACTIONS(202), 1,
      sym_identifier,
    ACTIONS(200), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1222] = 2,
    ACTIONS(206), 1,
      sym_identifier,
    ACTIONS(204), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1235] = 2,
    ACTIONS(210), 1,
      sym_identifier,
    ACTIONS(208), 7,
      ts_builtin_sym_end,
      anon_sym_DOT,
      sym_keyword,
      sym_binary_operator,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_RPAREN,
  [1248] = 5,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_binary_operator,
    ACTIONS(131), 1,
      sym_keyword,
    STATE(40), 1,
      aux_sym_keyword_message_repeat1,
    ACTIONS(212), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [1266] = 7,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_binary_operator,
    ACTIONS(131), 1,
      sym_keyword,
    ACTIONS(214), 1,
      anon_sym_DOT,
    ACTIONS(216), 1,
      anon_sym_RBRACE,
    STATE(40), 1,
      aux_sym_keyword_message_repeat1,
    STATE(77), 1,
      aux_sym_dynamic_array_repeat1,
  [1288] = 5,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_binary_operator,
    ACTIONS(131), 1,
      sym_keyword,
    STATE(40), 1,
      aux_sym_keyword_message_repeat1,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [1306] = 5,
    ACTIONS(116), 1,
      anon_sym_COLON_EQ,
    ACTIONS(118), 1,
      sym_binary_operator,
    ACTIONS(220), 1,
      anon_sym_PIPE,
    ACTIONS(222), 1,
      sym_identifier,
    ACTIONS(114), 3,
      anon_sym_DOT,
      sym_keyword,
      anon_sym_RBRACK,
  [1324] = 5,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_binary_operator,
    ACTIONS(131), 1,
      sym_keyword,
    STATE(40), 1,
      aux_sym_keyword_message_repeat1,
    ACTIONS(225), 2,
      anon_sym_DOT,
      anon_sym_RBRACE,
  [1341] = 5,
    ACTIONS(123), 1,
      sym_identifier,
    ACTIONS(125), 1,
      sym_binary_operator,
    ACTIONS(131), 1,
      sym_keyword,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
    STATE(40), 1,
      aux_sym_keyword_message_repeat1,
  [1357] = 3,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    ACTIONS(229), 1,
      anon_sym_DOT,
    STATE(88), 1,
      aux_sym_block_repeat2,
  [1367] = 3,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    ACTIONS(231), 1,
      anon_sym_DOT,
    STATE(79), 1,
      aux_sym_block_repeat2,
  [1377] = 3,
    ACTIONS(233), 1,
      sym_number,
    ACTIONS(235), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_byte_array_repeat1,
  [1387] = 3,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      aux_sym_method_repeat1,
  [1397] = 3,
    ACTIONS(237), 1,
      anon_sym_PIPE,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(80), 1,
      aux_sym_temporaries_repeat1,
  [1407] = 1,
    ACTIONS(218), 3,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [1413] = 3,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    ACTIONS(229), 1,
      anon_sym_DOT,
    STATE(90), 1,
      aux_sym_block_repeat2,
  [1423] = 3,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(87), 1,
      aux_sym_method_repeat1,
  [1433] = 3,
    ACTIONS(241), 1,
      anon_sym_PIPE,
    ACTIONS(243), 1,
      sym_block_argument,
    STATE(74), 1,
      aux_sym_block_repeat1,
  [1443] = 3,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(246), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      aux_sym_method_repeat1,
  [1453] = 3,
    ACTIONS(248), 1,
      sym_number,
    ACTIONS(251), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_byte_array_repeat1,
  [1463] = 3,
    ACTIONS(69), 1,
      anon_sym_RBRACE,
    ACTIONS(253), 1,
      anon_sym_DOT,
    STATE(83), 1,
      aux_sym_dynamic_array_repeat1,
  [1473] = 3,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    ACTIONS(255), 1,
      anon_sym_DOT,
    STATE(72), 1,
      aux_sym_block_repeat2,
  [1483] = 3,
    ACTIONS(63), 1,
      anon_sym_RBRACK,
    ACTIONS(257), 1,
      anon_sym_DOT,
    STATE(90), 1,
      aux_sym_block_repeat2,
  [1493] = 3,
    ACTIONS(259), 1,
      anon_sym_PIPE,
    ACTIONS(261), 1,
      sym_identifier,
    STATE(80), 1,
      aux_sym_temporaries_repeat1,
  [1503] = 3,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
    ACTIONS(231), 1,
      anon_sym_DOT,
    STATE(90), 1,
      aux_sym_block_repeat2,
  [1513] = 3,
    ACTIONS(264), 1,
      sym_number,
    ACTIONS(266), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_byte_array_repeat1,
  [1523] = 3,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
    ACTIONS(268), 1,
      anon_sym_DOT,
    STATE(83), 1,
      aux_sym_dynamic_array_repeat1,
  [1533] = 3,
    ACTIONS(271), 1,
      ts_builtin_sym_end,
    ACTIONS(273), 1,
      anon_sym_DOT,
    STATE(84), 1,
      aux_sym_method_repeat1,
  [1543] = 3,
    ACTIONS(84), 1,
      anon_sym_PIPE,
    ACTIONS(276), 1,
      sym_identifier,
    STATE(70), 1,
      aux_sym_temporaries_repeat1,
  [1553] = 3,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    ACTIONS(278), 1,
      anon_sym_DOT,
    STATE(81), 1,
      aux_sym_block_repeat2,
  [1563] = 3,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    STATE(84), 1,
      aux_sym_method_repeat1,
  [1573] = 3,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
    ACTIONS(278), 1,
      anon_sym_DOT,
    STATE(90), 1,
      aux_sym_block_repeat2,
  [1583] = 3,
    ACTIONS(282), 1,
      anon_sym_PIPE,
    ACTIONS(284), 1,
      sym_block_argument,
    STATE(74), 1,
      aux_sym_block_repeat1,
  [1593] = 3,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(289), 1,
      anon_sym_RBRACK,
    STATE(90), 1,
      aux_sym_block_repeat2,
  [1603] = 3,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(280), 1,
      ts_builtin_sym_end,
    STATE(75), 1,
      aux_sym_method_repeat1,
  [1613] = 2,
    ACTIONS(291), 1,
      anon_sym_SQUOTE,
    ACTIONS(293), 1,
      aux_sym_symbol_token1,
  [1620] = 1,
    ACTIONS(289), 2,
      anon_sym_DOT,
      anon_sym_RBRACK,
  [1625] = 1,
    ACTIONS(271), 2,
      ts_builtin_sym_end,
      anon_sym_DOT,
  [1630] = 1,
    ACTIONS(295), 1,
      anon_sym_SQUOTE,
  [1634] = 1,
    ACTIONS(297), 1,
      aux_sym_string_token1,
  [1638] = 1,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
  [1642] = 1,
    ACTIONS(65), 1,
      anon_sym_RBRACK,
  [1646] = 1,
    ACTIONS(59), 1,
      anon_sym_RBRACK,
  [1650] = 1,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
  [1654] = 1,
    ACTIONS(299), 1,
      ts_builtin_sym_end,
  [1658] = 1,
    ACTIONS(301), 1,
      sym_identifier,
  [1662] = 1,
    ACTIONS(303), 1,
      anon_sym_SQUOTE,
  [1666] = 1,
    ACTIONS(305), 1,
      sym_identifier,
  [1670] = 1,
    ACTIONS(307), 1,
      aux_sym_string_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 55,
  [SMALL_STATE(13)] = 110,
  [SMALL_STATE(14)] = 165,
  [SMALL_STATE(15)] = 220,
  [SMALL_STATE(16)] = 275,
  [SMALL_STATE(17)] = 327,
  [SMALL_STATE(18)] = 373,
  [SMALL_STATE(19)] = 419,
  [SMALL_STATE(20)] = 462,
  [SMALL_STATE(21)] = 505,
  [SMALL_STATE(22)] = 548,
  [SMALL_STATE(23)] = 591,
  [SMALL_STATE(24)] = 634,
  [SMALL_STATE(25)] = 677,
  [SMALL_STATE(26)] = 720,
  [SMALL_STATE(27)] = 743,
  [SMALL_STATE(28)] = 766,
  [SMALL_STATE(29)] = 784,
  [SMALL_STATE(30)] = 808,
  [SMALL_STATE(31)] = 825,
  [SMALL_STATE(32)] = 842,
  [SMALL_STATE(33)] = 859,
  [SMALL_STATE(34)] = 876,
  [SMALL_STATE(35)] = 893,
  [SMALL_STATE(36)] = 911,
  [SMALL_STATE(37)] = 927,
  [SMALL_STATE(38)] = 947,
  [SMALL_STATE(39)] = 963,
  [SMALL_STATE(40)] = 983,
  [SMALL_STATE(41)] = 1001,
  [SMALL_STATE(42)] = 1014,
  [SMALL_STATE(43)] = 1027,
  [SMALL_STATE(44)] = 1040,
  [SMALL_STATE(45)] = 1053,
  [SMALL_STATE(46)] = 1066,
  [SMALL_STATE(47)] = 1079,
  [SMALL_STATE(48)] = 1092,
  [SMALL_STATE(49)] = 1105,
  [SMALL_STATE(50)] = 1118,
  [SMALL_STATE(51)] = 1131,
  [SMALL_STATE(52)] = 1144,
  [SMALL_STATE(53)] = 1157,
  [SMALL_STATE(54)] = 1170,
  [SMALL_STATE(55)] = 1183,
  [SMALL_STATE(56)] = 1196,
  [SMALL_STATE(57)] = 1209,
  [SMALL_STATE(58)] = 1222,
  [SMALL_STATE(59)] = 1235,
  [SMALL_STATE(60)] = 1248,
  [SMALL_STATE(61)] = 1266,
  [SMALL_STATE(62)] = 1288,
  [SMALL_STATE(63)] = 1306,
  [SMALL_STATE(64)] = 1324,
  [SMALL_STATE(65)] = 1341,
  [SMALL_STATE(66)] = 1357,
  [SMALL_STATE(67)] = 1367,
  [SMALL_STATE(68)] = 1377,
  [SMALL_STATE(69)] = 1387,
  [SMALL_STATE(70)] = 1397,
  [SMALL_STATE(71)] = 1407,
  [SMALL_STATE(72)] = 1413,
  [SMALL_STATE(73)] = 1423,
  [SMALL_STATE(74)] = 1433,
  [SMALL_STATE(75)] = 1443,
  [SMALL_STATE(76)] = 1453,
  [SMALL_STATE(77)] = 1463,
  [SMALL_STATE(78)] = 1473,
  [SMALL_STATE(79)] = 1483,
  [SMALL_STATE(80)] = 1493,
  [SMALL_STATE(81)] = 1503,
  [SMALL_STATE(82)] = 1513,
  [SMALL_STATE(83)] = 1523,
  [SMALL_STATE(84)] = 1533,
  [SMALL_STATE(85)] = 1543,
  [SMALL_STATE(86)] = 1553,
  [SMALL_STATE(87)] = 1563,
  [SMALL_STATE(88)] = 1573,
  [SMALL_STATE(89)] = 1583,
  [SMALL_STATE(90)] = 1593,
  [SMALL_STATE(91)] = 1603,
  [SMALL_STATE(92)] = 1613,
  [SMALL_STATE(93)] = 1620,
  [SMALL_STATE(94)] = 1625,
  [SMALL_STATE(95)] = 1630,
  [SMALL_STATE(96)] = 1634,
  [SMALL_STATE(97)] = 1638,
  [SMALL_STATE(98)] = 1642,
  [SMALL_STATE(99)] = 1646,
  [SMALL_STATE(100)] = 1650,
  [SMALL_STATE(101)] = 1654,
  [SMALL_STATE(102)] = 1658,
  [SMALL_STATE(103)] = 1662,
  [SMALL_STATE(104)] = 1666,
  [SMALL_STATE(105)] = 1670,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 2),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_keyword_selector_repeat1, 2),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_keyword_selector_repeat1, 2), SHIFT_REPEAT(102),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_keyword_selector_repeat1, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_selector, 1),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword_selector, 1),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_temporaries, 2, .dynamic_precedence = 10),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_temporaries, 2, .dynamic_precedence = 10),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_temporaries, 2, .dynamic_precedence = 10), SHIFT(70),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_selector, 1),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_selector, 1),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_selector, 2),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binary_selector, 2),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_temporaries, 3, .dynamic_precedence = 10),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_temporaries, 3, .dynamic_precedence = 10),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selector, 1),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_selector, 1),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_keyword_message_repeat1, 2),
  [109] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_keyword_message_repeat1, 2), SHIFT_REPEAT(24),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_keyword_message_repeat1, 2),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primary, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primary, 1),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_keyword_message_repeat1, 2), SHIFT(24),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_message, 3),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_message, 2, .dynamic_precedence = -1),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_keyword_message, 2, .dynamic_precedence = -1), SHIFT(24),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_keyword_message, 2, .dynamic_precedence = -1),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_array, 4),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dynamic_array, 4),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 6),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 6),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 5),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_array, 5),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dynamic_array, 5),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 8),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 8),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parenthesized_expression, 3),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_message, 2),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unary_message, 2),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_byte_array, 3),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_byte_array, 3),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 7),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 7),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_byte_array, 2),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_byte_array, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 4),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 4),
  [196] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [198] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_array, 3),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dynamic_array, 3),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_symbol, 2),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_symbol, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_return, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_temporaries_repeat1, 1),
  [222] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_primary, 1), REDUCE(aux_sym_temporaries_repeat1, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dynamic_array_repeat1, 2),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2),
  [243] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(74),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 4),
  [248] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_byte_array_repeat1, 2), SHIFT_REPEAT(76),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_byte_array_repeat1, 2),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_temporaries_repeat1, 2),
  [261] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_temporaries_repeat1, 2), SHIFT_REPEAT(80),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [268] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dynamic_array_repeat1, 2), SHIFT_REPEAT(23),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2),
  [273] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2), SHIFT_REPEAT(9),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 3),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [286] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat2, 2), SHIFT_REPEAT(16),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat2, 2),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [299] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_smalltalk(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_keyword,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
